
# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.5
  - nightly
notifications:
  email: false

# Dummy script -- Windows only, so no tests.
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'

after_success:
  - julia -e 'Pkg.add("Documenter"); ENV["DOCUMENTER_DEBUG"] = "true"; cd(Pkg.dir("OpenDSSDirect")); include(joinpath("docs", "make.jl"))'